### ISSUE TITLE
java.lang.SecurityException Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=13846, uid=10326 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

### ISSUE THREAD

**Issue by ramona-cristea** [sw926/ImageFileSelector#18]
The library does not check correctly if app has the needed permission. 
For selecting image from gallery, in method ```selectorImage``` you are calling ```mPermissionsHelper.checkAndRequestPermission``` and pass the permission ```Manifest.permission.READ_EXTERNAL_STORAGE``` as parameter to be checked.  Inside this method, if android version is greater than M, you are doing a check calling ```isHavePermissions``` but in this method you do not pass further the permission which is being checked. 

As result, the app crashes after selecting picture from Gallery. 

android.os.Parcel.readException (Parcel.java:2004)
--
  | android.content.ContentResolver.query (ContentResolver.java:662)
  | com.sw926.imagefileselector.Compatibility.getDataColumn (Compatibility.java:117)
  | com.sw926.imagefileselector.Compatibility.getPath (Compatibility.java:77)
  | com.sw926.imagefileselector.ImagePickHelper.onActivityResult (ImagePickHelper.java:150)
  | com.sw926.imagefileselector.ImageFileSelector.onActivityResult (ImageFileSelector.java:99)

**Comment by sw926** [comment]
try this:
```
com.sw926.imagefileselector:library:1.0.14-SNAPSHOT
```

**Comment by ramona-cristea** [comment]
Hi @sw926. Thank you for the response! I tried that but I get Failed to resolve: com.sw926.imagefileselector:library:1.0.14-SNAPSHOT. Is it on Maven?
